version: "3"
services:
  mariadb:
    image: mariadb:10.0
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: "0.5G"
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 180s     
    environment:
        MYSQL_ROOT_PASSWORD: hadoop
    ports:
      - "3306:3306"
    networks:
      - kylonet
  elasticsearch:  
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1    
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.6"
          memory: "1.5G"
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 180s     
    environment:
#      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - kylonet
  activemq:
    image: rmohr/activemq:5.13.3
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.3"
          memory: "0.5G"
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 180s     
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - kylonet    
  kylo:
    image: dmalczyk/kylo-oracle:latest
    command: ["-d"]
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.3"
          memory: "6.5G"
      restart_policy:
        condition: none
        delay: 60s
        max_attempts: 3
        window: 180s        
    ports:
      - "8079:8079"
      - "8400:8400"
      - "8420:8420"
      - "8080:8080"
      - "8888:8888"
    networks:
      - kylonet
  oracle:
      image: wnameless/oracle-xe-11g:latest
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "0.5"
            memory: "1G"
        restart_policy:
          condition: on-failure
          delay: 60s
          max_attempts: 3
          window: 180s     
      ports:
        - "49160:22"
        - "49161:1521"
      networks:
        - kylonet
      environment:
        - "ORACLE_ALLOW_REMOTE=true"
volumes:
  esdata:
    driver: local
networks:
  kylonet: